name: download MSI

on:
  workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
#      - name: Create local directory
#        run: mkdir -p ./downloaded-files
        
      - name: Download from Private Repo
        env:
          GITHUB_TOKEN: dict=${{ secrets.SENTHIL_PAT }}
        run: |
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -L https://github.com/sentara-health/shp-834_IB_POST_ADDIN/raw/refs/heads/master/Compiled%20Objects%20for%20Deployment/SHP_IFPResponse_Setup.msi \
               -o ./downloaded-files/SHP_IFPResponse_Setup.msi
            
      - name: Upload msi as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SHP_IFPResponse_Setup.msi
          path: ./downloaded-files/SHP_IFPResponse_Setup.msi
  deploy:
      runs-on: self-hosted
      needs: [build]
      steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: C:\AzureDevops\DeploymentTest
