name: download MSI

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create local directory
        run: mkdir -p ./downloaded-files
        
      - name: Download file from private repo
        env:
          MY_PAT: ${{ secrets.SENTHIL_PAT }}
        run: |
          curl -sL \
            -H "Authorization: Bearer $MY_PAT" \
            -H "Accept: application/vnd.github.v3.raw" \
            https://github.com/sentara-health/837_IB_POST_ADDIN/raw/refs/heads/master/Deployment%20Artifacts/VPHP_837ImportPostProcess_setup.msi \
            -o downloaded-files/VPHP_837ImportPostProcess_setup.msi
            
      - name: Upload msi as artifact
        uses: actions/upload-artifact@v4
        with:
          name: VPHP_837ImportPostProcess_setup.msi
          path: ./downloaded-files/VPHP_837ImportPostProcess_setup.msi
  deploy:
      runs-on: self-hosted
      needs: [build]
      steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: C:\AzureDevops\DeploymentTest
