name: download MSI

on:
  workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Download from Private Repo
        run: |
          curl -L -H "Authorization: token ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}" \
            -o SHP_IFPResponse_Setup.msi \
            https://github.com/sentara-health/shp-834_IB_POST_ADDIN/raw/refs/heads/master/Compiled%20Objects%20for%20Deployment/SHP_IFPResponse_Setup.msi
      - name: Upload changed files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-msi
          path: changed_files/
  deploy:
      runs-on: self-hosted
      needs: [build]
      steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: C:\AzureDevops\DeploymentTest
