name: download MSI

on:
  workflow_dispatch
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Open Webpage on Windows Runner
        run: Start-Process "https://youtube.com"
        shell: powershell
