name: Java CI

on:
  push:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Remote Repository
        uses: actions/checkout@v4
        with:
          repository: AadhityaKumar/Tasks_Aadhitya_Kumar
          token: ${{ secrets.PAT }}
          ref: refs/pull/1/merge
          fetch-depth: 0
          path: repo
          
      - id: files2
        continue-on-error: true
        uses: jitterbit/get-changed-files@v1
        
      - run: |
          mkdir changed_files
          cd repo
          for changed_file in ${{ steps.files2.outputs.all}}; do
            cp --parents "$changed_file" changed_files/
          done
          
      - name: Upload changed files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pr-changed-files
          path: changed_files/
  deploy:
    runs-on: self-hosted
    needs: [build]
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        path: C:\AzureDevops\DeploymentTest
